server:
  port: 8089

spring:
  profiles:
    active: test
  application:
    name: car-service

  datasource:
    url: jdbc:mysql://localhost:3307/car-db
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/carsharing
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


openapi:
  oAuthFlow:
    tokenUrl: http://localhost:8080/realms/carsharing/protocol/openid-connect/token
  service:
    name: car-service
    version: 1.0.0
    description: Car service for working with cars
    url: http://localhost:8089

springdoc:
  show-actuator: true