server:
  port: 8089

spring:
  application:
    name: car-service

  datasource:
    url: jdbc:mysql://localhost:3307/car-db
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/carsharing
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs